### ISSUE TITLE
Support running kubernetes from OpenShift template

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#131]
Extend kubernetes provider so it could run an unaltered OpenShift template via inherit.

```
...
  - artifacts: 
      openshift: 
        - file:path/to/template.json
      kubernetes:
        inherit: openshift
...
```
