### ISSUE TITLE
You should be able to provide a default provider within Nulecule

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#378]
An issue that we're facing is that there is no way to assign a default provider __outside__ of the answers.conf.

If an Atomic App is packaged with only a Docker provider, by running `atomic run cdrage/testimage` the container by default will try to run k8s if no `answers.conf` is provided. 

I propose we add (somewhere) to the Nulecule graph a default provider.

```yaml
metadata:
  name: Hello Apache App
  appversion: 0.0.1
  description: Atomic app for deploying a really basic Apache HTTP server
graph:
  - name: helloapache-app
  - defaultprovider: docker
    params:
      - name: image
        description: The webserver image
        default: centos/httpd
      - name: hostport
        description: The host TCP port as the external endpoint
        default: 80
    artifacts:
      docker:
        - file://artifacts/docker/hello-apache-pod_run
      kubernetes:
        - file://artifacts/kubernetes/hello-apache-pod.json
```

**Comment by dustymabe** [comment]
seems reasonable. @vpavlin @goern ^^

**Comment by vpavlin** [comment]
IMO this should be added as a top level key - it is a "whole app" configuration. So something like:

```
---
specversion: 0.0.2
id: guestbook-app
defaultprovider: docker

metadata:
  name: Guestbook Application
  appversion: 0.0.1
  description: Atomic app for deploying the guestbook Python app
graph:
```

Or we just create another section like `metadata`

```
---
specversion: 0.0.2
id: guestbook-app

config:
  defaultprovider: docker

metadata:
  name: Guestbook Application
  appversion: 0.0.1
  description: Atomic app for deploying the guestbook Python app
graph:
```

Also, this is probably a spec change rather then just extension for Atomic App, so it should be a Nulecule repo issue:)

And last thing - provider choice is mostly on the user who deploys the app, not on the developer. If the app contains only a docker provider metadata, we should be able to figure this out (that's one of the purposes of the refactoring done by @rtnpro!) and change the behaviour accordingly - i.e. don't blindly try to talk to kubernetes if the app does not support it. 

If we agree that the paragraph above is what we are trying to solve here, then you have my +1 to work on it and fix it (and then the issue obviously belongs here). Otherwise, I'd like to hear more reasons to why the `defaultprovider` is needed in Nulecule file.

**Comment by charliedrage** [comment]
@vpavlin I totally agree in regards to the provider choice being able to select a default. If there is only __one__ provider it should default to it, or if there are two providers that aren't k8s, then it should default to at least one of them.

**Comment by vpavlin** [comment]
Can we also try to figure out which providers are available in the user's environment rather than hardcode this into an app?

**Comment by aweiteka** [comment]
I agree this should be a global config, not in the graph. I would suggest it land in the metadata section, not as a first level item.

@vpavlin we have a start towards auto-detection in #346

**Comment by aweiteka** [comment]
From an end-user perspective I think this scenario validates this as long as we can override the default via answers/cli opt.

1. I have a system that supports multiple providers, say kubernetes and Docker. I'm trying out a new application to play with it. I want the lowest barrier to get it running (hello, world). The quickstart docs suggest I can "just run it." I will rely on the default provider that's selected for this application. In this case the developer chose Docker as the default provider.
1. I have played with the application and now want to deploy it on a stage (pre-production) system. I have planned the deployment (storage requirements, config, etc) using documentation. I know what provider I want, this time kubernetes. I want to select which provider, overriding the default.

**Comment by kadel** [comment]
How about if we just say that first provider in ` io.projectatomic.nulecule.providers` label is default provider? This way we don't need another configuration option.

**Comment by vpavlin** [comment]
@kadel I think this splits metadata into 2 locations, which doesn't sound right to me. Also there have been some requests on being able to use Nulecule as a tar ball instead of Docker image and if somebody decides to do that, he would lose the ability to specify default provider

**Comment by rtnpro** [comment]
@vpavlin 

we don't need to add another key, as in

```
defaultprovider: docker
```

We just need to update Nulecule spec to support params in the root level, to incorporate params in ``general`` section in the Nulecule spec file.

**Comment by cdrage** [comment]
@rtnpro 

Could you post in https://github.com/projectatomic/nulecule/issues/184 about your proposal?

**Comment by cdrage** [comment]
timeout... ping @rtnpro

**Comment by vpavlin** [comment]
@rtnpro You are right

**Comment by rtnpro** [comment]
@cdrage Global params have been supported in atomicapp from a long time. We just need to update Nulecule spec docs.

**Comment by rtnpro** [comment]
@dustymabe, @vpavlin, do we have a go for updating Nulecule spec on this?

**Comment by rtnpro** [comment]
@vpavlin @aweiteka @goern @cdrage @dustymabe ping

**Comment by cdrage** [comment]
Hmm, so if global params are implemented, I'm assuming this will work just by passing `defaultprovider` correct?

**Comment by aweiteka** [comment]
Per [previous comments](https://github.com/projectatomic/nulecule/issues/184#issuecomment-158156406) I still recommend we make this an optional extension of the metadata. No spec change is needed. Ideally this is a fallback directive. atomicapp should intelligently determine the default based on capability and an ordered list. If nothing specified, try these providers in order if available.

**Comment by dustymabe** [comment]
So from aarons comment if we just use the metadata section then a spec file would look like this:

```yaml
metadata:
  name: Hello Apache App
  appversion: 0.0.1
  description: Atomic app for deploying a really basic Apache HTTP server
  defaultprovider: docker
...
```

That seems reasonable and wouldn't require an update to the spec. @rtnpro what would an example nulecule file look like if we implemented this in global params?

**Comment by rtnpro** [comment]
@dustymabe the above looks much cleaner compared to
```
params:
    - name: defaultprovider
      description: Default provider for your Nulecule app
      default: kubernetes
    ...
```
