### ISSUE TITLE
Cannot use "external" with "file://"

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#436]
Don't know if I'm doing something wrong here, but shouldn't this work?

```
---                                                                                                                                                                                                                                                            
specversion: 0.0.2                                                                                                                                                                                                                                             
id: helloapache-app                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
metadata:                                                                                                                                                                                                                                                      
  name: Hello Apache App                                                                                                                                                                                                                                       
  appversion: 0.0.1                                                                                                                                                                                                                                            
  description: Atomic app for deploying a really basic Apache HTTP server                                                                                                                                                                                      
graph:                                                                                                                                                                                                                                                         
  - name: nested-helloapache                                                                                                                                                                                                                                   
    source: file://external/nested-helloapache                                                                                                                                                                                                                 
  - name: helloapache-app                                                                                                                                                                                                                                      
    params:                                                                                                                                                                                                                                                    
      - name: image                                                                                                                                                                                                                                            
        description: The webserver image                                                                                                                                                                                                                       
        default: centos/httpd                                                                                                                                                                                                                                  
      - name: hostport                                                                                                                                                                                                                                         
        description: The host TCP port as the external endpoint                                                                                                                                                                                                
        default: 9090                                                                                                                                                                                                                                          
    artifacts:                                                                                                                                                                                                                                                 
      docker:                                                                                                                                                                                                                                                  
        - file://artifacts/docker/hello-apache-pod_run                                                                                                                                                                                                         
      kubernetes:                                                                                                                                                                                                                                              
        - file://artifacts/kubernetes/hello-apache-pod.json 
```

blocking #398
