### ISSUE TITLE
openshift undeploy doesn't properly select all pods from rc

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomicapp#484]
The undeploy code hardcodes `params = {"labelSelector": "deployment=%s" % name}`. Depending on the selector used by the user this might not be correct. In the case that I ran across this the selector I was using was just `name: etherpad` as shown below. We should detect what selector was used and use that instead of hardcoding `deployment` as it is now. 

This has the effect of not cleaning up the pods from an rc on undeploy(). 

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: etherpad
  labels:
    name: etherpad
spec:
  replicas: 1
  selector:
    name: etherpad
  template:
    metadata:
      labels:
        name: etherpad
    spec:
      containers:
        - name: etherpad
          image: $image
          ports:
            - name: etherpad-server
              containerPort: $hostport
          env:
            - name: DB_HOST
              value: $db_host
            - name: DB_DBID
              value: $db_name
            - name: DB_PASS
              value: $db_pass
            - name: DB_PORT
              value: '3306'
            - name: DB_USER
              value: $db_user
```
