### ISSUE TITLE
Defaulting to provider is unreliable

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomicapp#515]
`Utils.getSupportedProviders()` doesn't properly handle that artifacts could be inherited artifacts in the Nulecule file (an example is [here](https://github.com/projectatomic/nulecule-library/blob/feb892e0d7e7aa7c218334e9fa3028cb1db137c9/mariadb-centos7-atomicapp/Nulecule#L27)). I hit this issue when trying to add providers openshift support to the guestbook example. After adding the 'inherited' openshift I then wanted to use openshift but the code defaulted to use kubernetes because there is no `/artifacts/openshift` directory (added in b76acee).

We should probably get rid of this functionality once we can properly support setting a default provider within the global params like so:

```
params:
    - name: provider
      description: The provider that is used to deploy the application
      default: openshift
```

This doesn't currently work right now because our config handling is convoluted :(
