### ISSUE TITLE
provider in answers.conf defaults to "kubernetes" regardless of what's supported in Nulecule file

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#589]
The way it is now:

The "provider" in generated answers.conf always defaults to "kubernetes" regardless of what's supported in the Nulecule file.

The way it should be:

If only one provider is specified in the Nulecule file under artifacts, then that should be the default.  If multiple providers are specified but not Kubernetes, it should be None.

**Comment by jberkus** [comment]
BTW, when combined with  #562 this is particularly confusing to the user.

**Comment by dustymabe** [comment]
There is some history behind this: https://github.com/projectatomic/atomicapp/issues/380 and then https://github.com/projectatomic/atomicapp/issues/515

We opted to go with the fact that the application owner can set a default provider if they like within the parameters:

```
params:
    - name: provider
      description: The provider that is used to deploy the application
      default: openshift
```
