### ISSUE TITLE
atomicapp errors on missing user for k8s configuration

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#771]
If supplied with this:
```
apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8080
  name: dev
contexts:
- context:
    cluster: dev
    user: ""
  name: dev
current-context: dev
kind: Config
preferences: {}
users: []
```

With a blank user, atomicapp error's out.
